FROM node:12.13.1

WORKDIR /

ARG SAUCE_USERNAME
ARG SAUCE_ACCESS_KEY
ARG SAUCE_OWNER
ARG RUNS_ON_GITHUB
ARG SAUCE_API_BASE_URL
ARG BRANCH_NAME

ENV SAUCE_USERNAME=$SAUCE_USERNAME \
    SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY \
    SAUCE_OWNER=$SAUCE_OWNER \
    RUNS_ON_GITHUB=$RUNS_ON_GITHUB \
    SAUCE_API_BASE_URL=$SAUCE_API_BASE_URL \
    BRANCH_NAME=$BRANCH_NAME \
    TIMEFRAME=$TIMEFRAME

COPY index.js package.json package-lock.json ./
COPY src/ ./src

RUN npm install

ENTRYPOINT ["node", "/index.js"]
